name: Build and Deploy to Google Cloud

on:
  push:
    branches:
      - master  

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    env:
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }} 
      GCP_REGION: europe-north1  
      IMAGE_NAME: video-editor  
      DOCKER_TAG: latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud credentials
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker to use GCR
        run: |
          gcloud auth configure-docker
      - name: Build Docker image
        run: |
          docker build \
            -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.DOCKER_TAG }} .
      - name: Push Docker image
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.DOCKER_TAG }}
      - name: Deploy to Google Cloud Run
        run: |
          gcloud run deploy ${{ env.IMAGE_NAME }} \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.DOCKER_TAG }} \
            --platform managed \
            --region ${{ env.GCP_REGION }} \
            --allow-unauthenticated \
            --set-env-vars FFMPEG_PATH=/usr/bin/ffmpeg
